import { z } from "zod";
import { defineCapability, type CapabilityContext, type CapabilityResult } from "../../cli/types.js";
import { receiptPath } from "../../core/run/paths.js";
import { CapabilityError, EXIT, type Warning } from "../../core/run/receipt.js";
import { getStore, isStoreConfigured, recordParseDrift, StoreWriteError, upsertCompanyPeople, type CompanyPeopleUpsertResult, type StoreClient } from "../../core/store/index.js";
import { capability as companyProbe } from "../company.probe/index.js";
import { normalizeCompanyUrl } from "../company.probe/url.js";
import { sessionUrnsOf } from "../profile.capture/identity.js";
import { parseCompanyPeople, type CompanyCapture, type CompanyPeopleWarning } from "./parse.js";

const args = z.object({ url: z.string().min(1), limit: z.coerce.number().int().min(1).max(100).default(100), title: z.string().min(1).max(200).optional(), name: z.string().min(1).max(200).optional(), captureTimeoutMs: z.coerce.number().int().min(100).max(120_000).optional(), layoutTimeoutMs: z.coerce.number().int().min(10).max(120_000).optional() }).strict();
type PeopleArgs = z.infer<typeof args>; type PeopleContext = CapabilityContext<PeopleArgs, true>;
type CaptureArgs = Pick<PeopleArgs, "url" | "captureTimeoutMs" | "layoutTimeoutMs">;
export type PeopleCaptureExecution = { result: CapabilityResult; captures: CompanyCapture[]; sessionUrns: string[] };
export type CompanyPeopleDeps = { storeConfigured(): boolean; store(): StoreClient; upsert(rows: Parameters<typeof upsertCompanyPeople>[0], client: StoreClient): Promise<CompanyPeopleUpsertResult>; recordDrift(warnings: readonly CompanyPeopleWarning[], o: { client: StoreClient }): Promise<number>; capture(ctx: PeopleContext, args: CaptureArgs): Promise<PeopleCaptureExecution> };
const defaults: CompanyPeopleDeps = { storeConfigured: isStoreConfigured, store: getStore, upsert: (rows, client) => upsertCompanyPeople(rows, { client }), recordDrift: (warnings, o) => recordParseDrift(warnings, { client: o.client, capability: "company.people", shapeHash: null }), capture: async (ctx, captureArgs) => { const before = ctx.browser.tap.cursor; const result = await companyProbe.run({ ...ctx, args: { ...captureArgs, subpages: "people", scrolls: 0 } }); const captures = ctx.browser.tap.captures().filter((capture) => capture.seq >= before); return { result, captures, sessionUrns: sessionUrnsOf(captures) }; } };
function drift(code: string, evidence: string) { return new CapabilityError({ code, exit: EXIT.PARSE_DRIFT, action: "HALT_AND_NOTIFY", retryable: false, message: "captured bodies did not yield a trusted company subject", evidence }); }
function ordinary(warnings: readonly CompanyPeopleWarning[]): Warning[] { return warnings.map(({ code, field, n }) => ({ code, field, n })); }
export function createCompanyPeopleCapability(deps: CompanyPeopleDeps = defaults) { return defineCapability({ name: "company.people", risk: "read-cheap", needsBrowser: true, summary: "List people scoped to a company from captured Voyager search clusters.", args, cost: () => ({ page_loads: 1, search_pages: 0, profile_opens: 0 }), run: async (ctx) => {
  const target = normalizeCompanyUrl(ctx.args.url); const configured = deps.storeConfigured(); const client = configured ? deps.store() : ctx.flags.noStore ? null : deps.store();
  const captured = await deps.capture(ctx, { url: ctx.args.url, ...(ctx.args.captureTimeoutMs === undefined ? {} : { captureTimeoutMs: ctx.args.captureTimeoutMs }), ...(ctx.args.layoutTimeoutMs === undefined ? {} : { layoutTimeoutMs: ctx.args.layoutTimeoutMs }) });
  const evidence = receiptPath(ctx.run.paths.raw) + "/"; const parsed = parseCompanyPeople(captured.captures, { targetVanity: target.vanity, sessionUrns: captured.sessionUrns, limit: ctx.args.limit, ...(ctx.args.title ? { title: ctx.args.title } : {}), ...(ctx.args.name ? { name: ctx.args.name } : {}) });
  for (const item of parsed.warnings) ctx.run.log("parse.miss", { level: "warn", phase: "company.people", item_ref: target.ref, detail: item }); if (!parsed.ok) throw drift(parsed.warnings.some((w) => w.code === "PARSE_IDENTITY_IS_SESSION") ? "COMPANY_IDENTITY_IS_SESSION" : "COMPANY_IDENTITY_UNRESOLVED", evidence);
  let stored: CompanyPeopleUpsertResult | null = null; let driftRows = 0; if (!ctx.flags.noStore) { stored = await deps.upsert(parsed.people.map(({ company_urn, person_urn }) => ({ company_urn, person_urn })), client!); try { driftRows = await deps.recordDrift(parsed.warnings, { client: client! }); } catch (cause) { if (cause instanceof CapabilityError) throw new StoreWriteError(cause, stored.rows); throw cause; } }
  return { counts: { requested: ctx.args.limit, captured: captured.result.counts?.captured ?? captured.captures.length, usable: parsed.people.length, skipped: parsed.inspectedResults - parsed.people.length }, warnings: [...(captured.result.warnings ?? []), ...ordinary(parsed.warnings)], ...(stored ? { stored: { table: "company_people", run_ref: ctx.run.runId, rows: stored.rows } } : {}), data: { source: "voyager-body", profile_urls: parsed.people.map((p) => p.profile_url), inspected_results: parsed.inspectedResults, storage: stored ? { skipped: false, pair_rows: stored.rows, drift_rows: driftRows } : { skipped: true, reason: "--no-store" } }, next: stored ? `select cp.person_urn, p.vanity from company_people cp left join persons p on p.urn = cp.person_urn join companies c on c.urn = cp.company_urn where c.vanity = '${target.vanity.replaceAll("'", "''")}' order by cp.discovered_at desc limit ${ctx.args.limit}` : `read archived network bodies at ${evidence}` };
} }); }
export const capability = createCompanyPeopleCapability(); export default capability;
