import { describe, expect, it } from "vitest";
import { MAX_COMPANY_PEOPLE_FIELD_CHARS, MAX_COMPANY_PEOPLE_NODES, parseCompanyPeople, type CompanyCapture } from "./parse.js";
const company = "urn:li:fsd_company:42", p1 = "urn:li:fsd_profile:one", p2 = "urn:li:fsd_profile:two";
function island(v: unknown) { return `<code id="bpr-guid-1">${JSON.stringify(v).replaceAll("&", "&amp;").replaceAll('"', "&quot;")}</code>`; }
function result(urn: string, name = "Ada", headline = "Engineer", companyId = "42") { const ref = `urn:li:fsd_entityResultViewModel:(${urn},SEARCH_SRP,DEFAULT)`; return { ref, row: { entityUrn: ref, title: { text: name }, primarySubtitle: { text: headline }, navigationUrl: `https://www.linkedin.com/in/${urn.split(":").at(-1)}?x=1` }, filter: { parameterName: "currentCompany", secondaryFilterValues: [{ value: companyId, selected: true }] }, item: { item: { "*entityResult": ref } } }; }
function captures(rows: ReturnType<typeof result>[]): CompanyCapture[] { return [{ url: "https://www.linkedin.com/company/acme/people/", body: island({ included: [{ entityUrn: company, universalName: "acme" }] }) }, { url: "https://www.linkedin.com/voyager/api/graphql?org", body: JSON.stringify({ included: [{ entityUrn: company }] }) }, ...rows.map((r) => ({ url: "https://www.linkedin.com/voyager/api/graphql?search", body: JSON.stringify({ data: r.filter, included: [r.row], cluster: [r.item] }) }))]; }
const parse = (rows: ReturnType<typeof result>[], o: Partial<Parameters<typeof parseCompanyPeople>[1]> = {}) => parseCompanyPeople(captures(rows), { targetVanity: "acme", sessionUrns: [], limit: 100, ...o });
describe("parseCompanyPeople — pure contracts", () => {
  it("accepts only entity results in a subject-selected currentCompany cluster", () => { const good = result(p1), trap = result(p2, "Trap", "Other", "99"); const got = parse([good, trap]); expect(got.people.map((p) => p.person_urn)).toEqual([p1]); });
  it("excludes every session urn", () => { expect(parseCompanyPeople(captures([result(p1)]), { targetVanity: "acme", sessionUrns: [p1], limit: 100 }).people).toEqual([]); });
  it("filters name and title while bounding inspected capture work", () => { const got = parse([result(p1, "Ada One", "Engineer"), result(p2, "Ada Two", "Engineer")], { limit: 1, name: "ada", title: "engineer" }); expect(got.people).toHaveLength(1); expect(got.inspectedResults).toBe(1); });
  it("truncates a field with typed exit-5 drift", () => { const got = parse([result(p1, "x".repeat(MAX_COMPANY_PEOPLE_FIELD_CHARS + 3))]); expect(got.people[0]?.name).toHaveLength(MAX_COMPANY_PEOPLE_FIELD_CHARS); expect(got.warnings).toContainEqual(expect.objectContaining({ field: "name", n: 3, exit: 5 })); });
  it("says so when no captured body carries the subject's currentCompany filter", () => { const drifted = result(p1); drifted.filter.parameterName = "renamedFilter"; const got = parse([drifted]); expect(got.people).toEqual([]); expect(got.warnings).toContainEqual(expect.objectContaining({ code: "PARSE_SCOPE_UNMATCHED", field: "current_company_filter", exit: 5 })); });
  it("bounds capture bodies", () => { const got = parseCompanyPeople([...captures([result(p1)]), ...Array.from({ length: 260 }, () => ({ url: "https://x.invalid", body: "{}" }))], { targetVanity: "acme", sessionUrns: [], limit: 1 }); expect(got.warnings).toContainEqual(expect.objectContaining({ field: "captures", exit: 5 })); });
  it("bounds JSON nodes", () => { const huge = { url: "https://www.linkedin.com/voyager/api/graphql", body: JSON.stringify(Array.from({ length: MAX_COMPANY_PEOPLE_NODES + 1 }, () => null)) }; const got = parseCompanyPeople([...captures([result(p1)]), huge], { targetVanity: "acme", sessionUrns: [], limit: 2 }); expect(got.warnings).toContainEqual(expect.objectContaining({ field: "nodes", exit: 5 })); });
});
